version: "3"
services:
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345678910
      POSTGRES_USER: CliffLin
      POSTGRES_DB: postgres-vue

  app:
    image: my-node-app
    ports:
      - 1300:3000